#!/bin/bash

Main() {
    	source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    	local command=(
        	eos_yad --title="EndeavourOS i3-wm keybindings:" --no-buttons --geometry=400x175-15-400 --list
        	--column=HELP
        	"ESC to close this window"
        	" =  = Modkey"
 		" + t to start Kitty terminal"
		" + q to close the currently focused application" 
		" + z to open the applications menu"
		" + F1 to get more info on this i3wm config"
		       )

	"${command[@]}"
	}

Main "$@"
